### ISSUE TITLE
Remove unneeded pages

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#11]
There are a [bunch of pages](https://github.com/codeforamerica/brigade/tree/master/app/views/pages) on the old Brigade site. We need to decide which ones can be removed.

I've already pulled almost all of the pages and content over and put it into a minimal html skeleton. http://codeforamerica.github.io/brigade-alpha/activities/ as an example.

Before we spend a bunch of time designing these to look better, we should remove the ones we don't need.
#### Tasks
- [x] Check the Google Analytics for the Brigade site.
- [x] Check with Brigade team which ones they want.
- [ ] Ask Captains which ones they use?
- [ ] Destroy nonuseful pages without remorse.
