### ISSUE TITLE
Be able to link to individual Brigades

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#13]
#### Description

A Brigade member should be able to share a link to new Brigade website with their Brigade's overlay visible. Adding #Open Oakland to the url should then show.
![screen shot 2014-03-20 at 11 05 17 am](https://f.cloud.github.com/assets/595778/2475701/4e17a99c-b05a-11e3-8778-1f34693d3282.png)
#### Files

js/map.js
##### Tasks
- [x] Decide what makes the prettiest urls. #Open Oakland or ?name=Open Oakland.
- [x] Once the API call is loaded, parse out the Brigade name from the URL.
- [x] Match the anchor tag to the Brigade name.
- [x] Pass updateOverlay() the matching Brigade object.
