### ISSUE TITLE
Add Stories, Events, and Projects to Brigade overlay

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#3]
#### Details

Using this [sample API response](https://github.com/codeforamerica/civic-json-worker/issues/19) add in stories, events, and projects onto the Brigade overlay. Make up data for anything missing.
#### Files

js/map.js
#### Tasks
- [ ] Use the "lastest_story" attribute for a story. It should have a headline and a link.
- [ ] Use the "next_event" attribute for an event. It should be the name and a link.
- [ ] Use the "two_active_projects" to show two projects. They'll be the names and links to live sites or GitHub.
