### ISSUE TITLE
Add a sign up form for the mobile view

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#45]
#### Description

The mobile view doesn't have a sign up form at the moment. We should add one.
#### Task
- [ ] Copy the form from overlay-home.php
- [ ] Add it to brigades-list.php under the #brigade-list-mobile element.
- [ ] Hide it behind a join button.
